apiVersion: v1
kind: Pod
metadata:
  name: terry-nginx-pod
  labels:
    app: nginx
    owner: terrybright80
    environment: dev
spec: 
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: terry-nginx-service
  labels:
    owner: terrybright80
    environment: dev
  annotations:
    description: "NodePort service for Terry's nginx pod"
spec:
  type: NodePort     #ClusterIP, LoadBalancer
  selector:
    app: nginx  # Matches the Pod's label
  ports:
    - port: 80       # Service port (cluster-internal)
      targetPort: 80 # Pod's containerPort
      nodePort: 30010 # Optional: Manually chosen port (30000-32767)
