---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app9000
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app9000
  template:
    metadata:
      labels:
        app: app9000
    spec:
      containers:
      - name: app9000
        image: liontechacademy/sonarqube:20250903-200853
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: app9000-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: app9000
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30090  # You can choose a port between 30000-32767 or omit for auto-assignment