apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: class32
subjects:
- kind: User
  name: class34
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: class34
  apiGroup: rbac.authorization.k8s.io